language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: make test
addons:
  sauce_connect: true
env:
  global:
  - secure: gvuyYRFMreAdTdq27uPJ1sG8mMqc4ucTFC3PnM1M/vNAwEyYdLKIMTSJ5s8nfszkl3Ysp+4CD3L3NmF0EEsPPpaFdCngC0XfGwaaPo5L4KJ8iYZP+gWXxu3xqlW0wPXlPYFjQB27mdJDbCkZN6b20v3l39J8PJxXyX7XBHzL21Y=
  - secure: Inq6/qMA2PNEW2HIQGlHDF1Z5YXVxMFgQvPFbZCQBvBw9e1Um7Gq36qyAd9M5/2OYOaHP+S2D6P24Ex4HRHU3rIjGh5HTdoOgZZf9h7c7o8gAJ+TCMS0K2cH03Mu+XWaJfnzPhjiFYJNwWFGXMRcqcSTTYgYO8hicTiZBI5QtX4=
  - secure: QMyArbfM+lWsfZLq36hyvoeM+C5nIU5+1h8AduQ+QGBMwOISr6F6qA6lmVgIToQ1mW8ymiNo75nW6wIVr/pCK9uJaOheTwNHoo9Pmzr+sAXxpRqOpQGjPdR/2/swQ6Y0Thsr9+tjm4yHj2d75jJU+IkI1iB0vnES6Y3gsuF+0rg=
